services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules

  client:
    build:
      context: ./client/cattagram
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client/cattagram:/app
      - client_node_modules:/app/node_modules

volumes:
  client_node_modules:
  api_node_modules: