ARG NODE_VERSION=25.8.1-alpine

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

RUN npm install json-server

COPY messages.json .
RUN chown -R node:node /app

USER node

EXPOSE 3000

CMD ["npx", "json-server", "messages.json", "-h", "0.0.0.0"]
